version: "2.4"
services:
  #  logspout:
  #    image: gliderlabs/logspout:v3
  #    restart: always
  #    command: 'syslog://${SERVER_ADDRESS}:5140/udp'
  #    volumes:
  #      - '/var/run/docker.sock:/var/run/docker.sock'
  client_interface:
    image: mtcpartners/client_interface:0.1
    ports:
      - "50050:50050"
    restart: always
    mem_limit: 6g
    networks:
      - webnet
    environment:
      - LOGGING_LEVEL
      - SERVER_ADDRESS
      - SERVER_PORT
      - CLIENT_INTERFACE_PORT
      - PARTNER_NAME
      - TESTING
      - CLIENT_SECRET
      - SERVER=0
  node_worker_interface:
    image: mtcpartners/nodeserver:0.2
    mem_limit: 6g
    restart: always
    networks:
      - webnet
    environment:
      - LOGGING_LEVEL=20
      - SERVER_ADDRESS=${CLIENT_INTERFACE_SERVER_ADDRESS}
      - SERVER_PORT=${CLIENT_INTERFACE_PORT}
      - PARTNER_NAME
      - CLIENT_SECRET
      - DATA_SOURCE
      - STATIC_VARIABLES_FILE_PATH
      - TESTING
      - DATA_WRAPPER_URL
      - SERVER=0
    depends_on:
      - client_interface
networks:
  webnet:
    name: webnet