version: "3.7"
services:
  logspout:
    image: gliderlabs/logspout:v3
    restart: always
    command: 'syslog://${SERVER_ADDRESS}:5140/udp'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  node_worker:
    image: mtcpartners/nodeserver:0.1
    restart: always
    networks:
      - webnet
    environment:
      - LOGGING_LEVEL
      - SERVER_ADDRESS
      - PARTNER_NAME
      - CLIENT_SECRET
    depends_on:
      - logspout
networks:
  webnet:
    name: webnet